[package]
name = "lotus-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30", features = ["rwh_05"] }
env_logger = "0.11.6"
log = "0.4.26"
wgpu = "24.0"
pollster = "0.4"
bytemuck = { version = "1.21.0", features = [ "derive" ] }
