[package]
name = "lotus-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "24.0.1"
winit = { version = "0.30", default-features = false, features = ["rwh_06"] }
accesskit_winit = { version = "0.23", default-features = false, features = [
  "rwh_06",
] }
raw-window-handle = "0.6"
serde = { version = "1.0", features = ["derive"], optional = true }
